<script src="<?=SITE_PATH?>js/jquery.min.js"></script>
<script src="<?=SITE_PATH?>js/jquery-1.7.1.min.js"></script>
<script src="<?=SITE_PATH?>js/jquery.cookie.js"></script>
<script src="<?=SITE_PATH?>js/bootstrap.min.js"></script>
<script src="<?=SITE_PATH?>js/wow.min.js"></script>
<script src="<?=SITE_PATH?>js/slidebars.js"></script>
<script src="<?=SITE_PATH?>js/jquery.bxslider.min.js"></script>
<script src="<?=SITE_PATH?>js/holder.js"></script>
<script src="<?=SITE_PATH?>js/buttons.js"></script>
<script src="<?=SITE_PATH?>js/styleswitcher.js"></script>
<script src="<?=SITE_PATH?>js/jquery.mixitup.min.js"></script>
<script src="<?=SITE_PATH?>js/circles.min.js"></script>
<script src="<?=SITE_PATH?>js/shCore.js"></script>
<script src="<?=SITE_PATH?>js/shBrushXml.js"></script>
<script src="<?=SITE_PATH?>js/shBrushJScript.js"></script> 
<script src="<?=SITE_PATH?>js/app.js"></script>
<script src="<?=SITE_PATH?>js/index.js"></script>
